/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import shopify from "strapi-plugin-shopify/strapi-admin";
import shopifyFields from "strapi-plugin-shopify-fields/strapi-admin";
import strapiStripe from "strapi-stripe/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "strapi-cloud": strapiCloud,
    i18n: i18N,
    "users-permissions": usersPermissions,
    shopify: shopify,
    "shopify-fields": shopifyFields,
    "strapi-stripe": strapiStripe,
  },
});
